### ISSUE TITLE
Deployment fails on `ceph orch host add minion`

### ISSUE THREAD

**Issue by bk201** [ceph/ceph-salt#139]
## How to reproduce
Use sesdev to create an octopus env:
```
sesdev create octopus --single-node --ceph-salt-repo https://github.com/ceph/ceph-salt.git --ceph-salt-branch master  mini
```

## Error messages:

salt
```
[2020-03-25 06:31:00.845564] [master.mini.com ] [STEP ] [END  ] Run cephadm bootstrap
[2020-03-25 06:31:01.322569] [master.mini.com ] [STEP ] [BEGIN] Configure SSH orchestrator
[2020-03-25 06:31:08.132525] [master.mini.com ] Finished with failures

Failure in minion: master.mini.com
__id__: configure ssh orchestrator
__run_num__: 52
__sls__: ceph-salt.cephbootstrap
changes:
  pid: 6992
  retcode: 2
  stderr: 'set mgr/cephadm/ssh_identity_key

    set mgr/cephadm/ssh_identity_pub

    Error ENOENT: Failed to connect to master (master).  Check that the host is reachable
    and accepts connections using the cephadm SSH key'
  stdout: ''
comment: 'Command "ceph config-key set mgr/cephadm/ssh_identity_key -i ~/.ssh/id_rsa

  ceph config-key set mgr/cephadm/ssh_identity_pub -i ~/.ssh/id_rsa.pub

  ceph mgr module enable cephadm && \

  ceph orch set backend cephadm && \


  ceph orch host add master && \

```

mgr
```
Mar 25 07:31:08 master bash[5143]: cephadm 2020-03-25T06:31:07.136274+0000 mgr.master.sbekio (mgr.14143) 3 : cephadm [ERR] _Promise failed
Mar 25 07:31:08 master bash[5143]: Traceback (most recent call last):
Mar 25 07:31:08 master bash[5143]:   File "/usr/lib/python3.6/site-packages/execnet/gateway_bootstrap.py", line 45, in bootstrap_exec
Mar 25 07:31:08 master bash[5143]:     s = io.read(1)
Mar 25 07:31:08 master bash[5143]:   File "/usr/lib/python3.6/site-packages/execnet/gateway_base.py", line 389, in read
Mar 25 07:31:08 master bash[5143]:     "expected %d bytes, got %d" % (numbytes, len(buf)))
Mar 25 07:31:08 master bash[5143]: EOFError: expected 1 bytes, got 0
Mar 25 07:31:08 master bash[5143]: During handling of the above exception, another exception occurred:
Mar 25 07:31:08 master bash[5143]: Traceback (most recent call last):
Mar 25 07:31:08 master bash[5143]:   File "/usr/share/ceph/mgr/cephadm/module.py", line 1544, in _run_cephadm
Mar 25 07:31:08 master bash[5143]:     conn, connr = self._get_connection(addr)
Mar 25 07:31:08 master bash[5143]:   File "/usr/share/ceph/mgr/cephadm/module.py", line 1507, in _get_connection
Mar 25 07:31:08 master bash[5143]:     ssh_options=self._ssh_options)
Mar 25 07:31:08 master bash[5143]:   File "/usr/lib/python3.6/site-packages/remoto/backends/__init__.py", line 34, in __init__
Mar 25 07:31:08 master bash[5143]:     self.gateway = self._make_gateway(hostname)
Mar 25 07:31:08 master bash[5143]:   File "/usr/lib/python3.6/site-packages/remoto/backends/__init__.py", line 44, in _make_gateway
Mar 25 07:31:08 master bash[5143]:     self._make_connection_string(hostname)
Mar 25 07:31:08 master bash[5143]:   File "/usr/lib/python3.6/site-packages/execnet/multi.py", line 128, in makegateway
Mar 25 07:31:08 master bash[5143]:     gw = gateway_bootstrap.bootstrap(io, spec)
Mar 25 07:31:08 master bash[5143]:   File "/usr/lib/python3.6/site-packages/execnet/gateway_bootstrap.py", line 98, in bootstrap
Mar 25 07:31:08 master bash[5143]:     bootstrap_exec(io, spec)
Mar 25 07:31:08 master bash[5143]:   File "/usr/lib/python3.6/site-packages/execnet/gateway_bootstrap.py", line 50, in bootstrap_exec
Mar 25 07:31:08 master bash[5143]:     raise HostNotFound(io.remoteaddress)
Mar 25 07:31:08 master bash[5143]: execnet.gateway_bootstrap.HostNotFound: -F /tmp/cephadm-conf-z6cd7m8u -i /tmp/cephadm-identity-ic8iqwk6 root@master
Mar 25 07:31:08 master bash[5143]: The above exception was the direct cause of the following exception:
Mar 25 07:31:08 master bash[5143]: Traceback (most recent call last):
Mar 25 07:31:08 master bash[5143]:   File "/usr/share/ceph/mgr/cephadm/module.py", line 444, in do_work
Mar 25 07:31:08 master bash[5143]:     res = self._on_complete_(*args, **kwargs)
Mar 25 07:31:08 master bash[5143]:   File "/usr/share/ceph/mgr/cephadm/module.py", line 512, in <lambda>
Mar 25 07:31:08 master bash[5143]:     return cls(on_complete=lambda x: f(*x), value=args, name=name, **c_kwargs)
Mar 25 07:31:08 master bash[5143]:   File "/usr/share/ceph/mgr/cephadm/module.py", line 1645, in add_host
Mar 25 07:31:08 master bash[5143]:     error_ok=True, no_fsid=True)
Mar 25 07:31:08 master bash[5143]:   File "/usr/share/ceph/mgr/cephadm/module.py", line 1620, in _run_cephadm
Mar 25 07:31:08 master bash[5143]:     raise OrchestratorError('Failed to connect to %s (%s).  Check that the host is reachable and accepts connections using the cephadm S>
Mar 25 07:31:08 master bash[5143]: orchestrator._interface.OrchestratorError: Failed to connect to master (master).  Check that the host is reachable and accepts conn
```

**Comment by bk201** [comment]
Try connecting in container:
```
master:/ # ssh -F /tmp/cephadm-conf-z6cd7m8u -i /tmp/cephadm-identity-ic8iqwk6 root@master
Warning: Permanently added 'master,10.20.47.200' (ECDSA) to the list of known hosts.
ssh_dispatch_run_fatal: Connection to 10.20.47.200 port 22: error in libcrypto
```

**Comment by bk201** [comment]
I did `zypper update` both in container image and host and the deployment succeeded.
Not sure which package is root cause.

**Comment by smithfarm** [comment]
> I did `zypper update` both in container image and host and the deployment succeeded.
> Not sure which package is root cause.

Thanks for looking into this @bk201 

Sounds like the conclusion is, as Kris said in the chat, "we just need to wait for OBS to actually rebuild the images."

**Comment by smithfarm** [comment]
```
master:~ # podman run --rm --net=host -it f56582c877e7 /bin/bash
master:/ # zypper ref
Retrieving repository 'Non-OSS Repository' metadata ............................................................................[done]
Building repository 'Non-OSS Repository' cache .................................................................................[done]
Retrieving repository 'Main Repository' metadata ...............................................................................[done]
Building repository 'Main Repository' cache ....................................................................................[done]
Retrieving repository 'Main Update Repository' metadata ........................................................................[done]
Building repository 'Main Update Repository' cache .............................................................................[done]
Retrieving repository 'Update Repository (Non-Oss)' metadata ...................................................................[done]
Building repository 'Update Repository (Non-Oss)' cache ........................................................................[done]
All repositories have been refreshed.
master:/ # zypper up
Loading repository data...
Warning: Repository 'Update Repository (Non-Oss)' appears to be outdated. Consider using a different mirror or server.
Reading installed packages...

The following 70 packages are going to be upgraded:
  aaa_base bash coreutils cpio cracklib cracklib-dict-small file-magic findutils gawk glibc grep info libacl1 libattr1 libaudit1
  libblkid1 libbz2-1 libcap-ng0 libcap2 libcom_err2 libcrack2 libcurl4 libdw1 libebl-plugins libelf1 libfdisk1 libgcc_s1 libgcrypt20
  libglib-2_0-0 libgmp10 libgpg-error0 libkeyutils1 liblua5_3-5 liblzma5 libmagic1 libmount1 libncurses6 libnghttp2-14 libnsl2
  libopenssl1_1 libpcre1 libpopt0 libreadline7 libselinux1 libsemanage1 libsepol1 libsmartcols1 libstdc++6 libtirpc-netconfig
  libtirpc3 libutempter0 libuuid1 libverto1 libz1 libzio1 ncurses-utils openSUSE-release openssl-1_1 pam perl-base permissions rpm sed
  shadow system-group-hardware system-user-root sysuser-shadow terminfo-base update-alternatives util-linux

The following product is going to be reinstalled:
  "openSUSE Leap 15.2"

The following 2 packages require a system reboot:
  glibc libopenssl1_1

70 packages to upgrade.
Overall download size: 19.9 MiB. Already cached: 0 B. After the operation, additional 110.9 KiB will be used.

    Note: System reboot required.
Continue? [y/n/v/...? shows all options] (y): ^C
```

**Comment by bk201** [comment]
I can narrow down the update-required package to `libopenssl1_1` in container image only.
Updating in host is not required.

**Comment by sebastian-philipp** [comment]
```
master:~ # ceph orch host add master
Error ENOENT: Failed to connect to master (master).  Check that the host is reachable and accepts connections using the cephadm SSH key
master:~ # cephadm enter --name mgr.master.mwvqjn --fsid 035abdb4-6f6b-11ea-b577-525400d426e0
[ceph: root@master /]# zypper up libopenssl1_1
Building repository 'Non-OSS Repository' cache .......................................................................................................................................................................................................[done]
Building repository 'Main Repository' cache ..........................................................................................................................................................................................................[done]
Building repository 'Main Update Repository' cache ...................................................................................................................................................................................................[done]
Building repository 'Update Repository (Non-Oss)' cache ..............................................................................................................................................................................................[done]
Loading repository data...
Warning: Repository 'Update Repository (Non-Oss)' appears to be outdated. Consider using a different mirror or server.
Reading installed packages...
Resolving package dependencies...

The following package is going to be upgraded:
  libopenssl1_1

The following package requires a system reboot:
  libopenssl1_1

1 package to upgrade.
Overall download size: 1.3 MiB. Already cached: 0 B. After the operation, additional 100.4 KiB will be used.

    Note: System reboot required.
Continue? [y/n/v/...? shows all options] (y): y
Retrieving package libopenssl1_1-1.1.1d-lp152.4.1.x86_64                                                                                                                                                               (1/1),   1.3 MiB (  3.5 MiB unpacked)
Retrieving: libopenssl1_1-1.1.1d-lp152.4.1.x86_64.rpm ................................................................................................................................................................................................[done]

Checking for file conflicts: .........................................................................................................................................................................................................................[done]
(1/1) Installing: libopenssl1_1-1.1.1d-lp152.4.1.x86_64 ..............................................................................................................................................................................................[done]
 
Core libraries or services have been updated.
Reboot is required to ensure that your system benefits from these updates.
[ceph: root@master /]# exit
master:~ # ceph orch host add master
Added host 'master'
master:~ # 
```
oneliner
```bash
cephadm enter --name $(cephadm ls | jq -r '.[].name' | grep mgr) -- zypper up -y libopenssl1_1
```

works as well:

```diff
master:/ # diff -u cephbootstrap.sls  srv/salt/ceph-salt/cephbootstrap.sls
--- cephbootstrap.sls   2020-03-26 17:30:40.928718832 +0100
+++ srv/salt/ceph-salt/cephbootstrap.sls        2020-03-26 17:25:40.995740950 +0100
@@ -65,11 +61,12 @@
     - failhard: True
 {% endif %}
 
-{{ macros.begin_step('Configure SSH orchestrator') }}
+{{ macros.begin_step('Configure cephadm MGR module') }}
 
 configure ssh orchestrator:
   cmd.run:
     - name: |
+        cephadm enter --name $(cephadm ls | jq -r '.[].name' | grep mgr) -- zypper up -y libopenssl1_1
         ceph config-key set mgr/cephadm/ssh_identity_key -i ~/.ssh/id_rsa
         ceph config-key set mgr/cephadm/ssh_identity_pub -i ~/.ssh/id_rsa.pub
         ceph mgr module enable cephadm && \
@@ -82,8 +79,8 @@
       - cmd: run cephadm bootstrap
     - failhard: True
 
-{{ macros.end_step('Configure SSH orchestrator') }}
+{{ macros.end_step('Configure cephadm MGR module') }}
 
 {% endif %}
 
-{{ macros.end_stage('Ceph bootstrap') }}
+{{ macros.end_stage('Bootstrap the Ceph cluster') }}
master:/ # 
```

**Comment by smithfarm** [comment]
This is no longer reproducible now that OBS caught up with its backlog. I'll go ahead and close it.
