### ISSUE TITLE
'ceph-salt config' if 'pgrep' is not available

### ISSUE THREAD

**Issue by ricardoasmarques** [ceph/ceph-salt#368]
```
blueshark-1:~ # ceph-salt config
Traceback (most recent call last):
File "/usr/bin/ceph-salt", line 11, in <module>
load_entry_point('ceph-salt==15.2.9+1597076758.g9c0ce9f', 'console_scripts', 'ceph-salt')()
File "/usr/lib/python3.6/site-packages/ceph_salt/__init__.py", line 23, in ceph_salt_main
cli(prog_name='ceph-salt')
File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
return self.main(*args, **kwargs)
File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
rv = self.invoke(ctx)
File "/usr/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
return callback(*args, **kwargs)
File "/usr/lib/python3.6/site-packages/ceph_salt/__init__.py", line 58, in config_shell
if not run_config_shell():
File "/usr/lib/python3.6/site-packages/ceph_salt/config_shell.py", line 1275, in run_config_shell
if not check_config_prerequesites():
File "/usr/lib/python3.6/site-packages/ceph_salt/config_shell.py", line 1228, in check_config_prerequesites
check_salt_master_status()
File "/usr/lib/python3.6/site-packages/ceph_salt/validate/salt_master.py", line 82, in check_salt_master_status
check_salt_master()
File "/usr/lib/python3.6/site-packages/ceph_salt/validate/salt_master.py", line 49, in check_salt_master
count = subprocess.check_output(['pgrep', '-c', 'salt-master'])
File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
**kwargs).stdout
File "/usr/lib64/python3.6/subprocess.py", line 423, in run
with Popen(*popenargs, **kwargs) as process:
File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
restore_signals, start_new_session)
File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 5] Input/output error: 'pgrep'
```

**Comment by ricardoasmarques** [comment]
`procps` is already included in the spec file, so this issue should not happen:
https://github.com/ceph/ceph-salt/blob/master/ceph-salt.spec#L63
