### ISSUE TITLE
ceph-salt issues invalid ceph command

### ISSUE THREAD

**Issue by jan--f** [ceph/ceph-salt#413]
```
INFO:cephadm:Non-zero exit code 22 from /usr/bin/podman run --rm --net=host --ipc=host -e CONTAINER_IMAGE=registry.suse.de/suse/containers/ses/7/containers/ses/7/ceph/ceph:15.2.0.108 -e NODE_NAME=master -v /var/log/ceph/04e70252-0307-11eb-a869-5254000f2082:/var/log/ceph:z -v /tmp/ceph-tmphn401fmr:/etc/ceph/ceph.client.admin.keyring:z -v /tmp/ceph-tmpl4kq9mr5:/etc/ceph/ceph.conf:z -v /home/cephadm/.ssh/id_rsa:/tmp/cephadm-ssh-key:z -v /home/cephadm/.ssh/id_rsa.pub:/tmp/cephadm-ssh-key.pub:z --entrypoint /usr/bin/ceph registry.suse.de/suse/containers/ses/7/containers/ses/7/ceph/ceph:15.2.0.108 cephadm set-priv-key -i /tmp/cephadm-ssh-key
INFO:cephadm:/usr/bin/ceph:stderr no valid command found; 9 closest matches:
INFO:cephadm:/usr/bin/ceph:stderr cephadm set-ssh-config
INFO:cephadm:/usr/bin/ceph:stderr cephadm clear-ssh-config
INFO:cephadm:/usr/bin/ceph:stderr cephadm get-ssh-config
INFO:cephadm:/usr/bin/ceph:stderr cephadm generate-key
INFO:cephadm:/usr/bin/ceph:stderr cephadm clear-key
INFO:cephadm:/usr/bin/ceph:stderr cephadm get-pub-key
INFO:cephadm:/usr/bin/ceph:stderr cephadm get-user
INFO:cephadm:/usr/bin/ceph:stderr cephadm check-host <host> [<addr>]
INFO:cephadm:/usr/bin/ceph:stderr cephadm prepare-host <host> [<addr>]
INFO:cephadm:/usr/bin/ceph:stderr Error EINVAL: invalid command
Traceback (most recent call last):
  File "/usr/sbin/cephadm", line 5758, in <module>
    r = args.func()
  File "/usr/sbin/cephadm", line 1213, in _default_image
    return func()
  File "/usr/sbin/cephadm", line 2889, in command_bootstrap
    cli(['cephadm', 'set-priv-key', '-i', '/tmp/cephadm-ssh-key'], extra_mounts=mounts)
  File "/usr/sbin/cephadm", line 2754, in cli
    ).run(timeout=timeout)
  File "/usr/sbin/cephadm", line 2417, in run
    self.run_cmd(), desc=self.entrypoint, timeout=timeout)
  File "/usr/sbin/cephadm", line 874, in call_throws
    raise RuntimeError('Failed command: %s' % ' '.join(command))
RuntimeError: Failed command: /usr/bin/podman run --rm --net=host --ipc=host -e CONTAINER_IMAGE=registry.suse.de/suse/containers/ses/7/containers/ses/7/ceph/ceph:15.2.0.108 -e NODE_NAME=master -v /var/log/ceph/04e70252-0307-11eb-a869-5254000f2082:/var/log/ceph:z -v /tmp/ceph-tmphn401fmr:/etc/ceph/ceph.client.admin.keyring:z -v /tmp/ceph-tmpl4kq9mr5:/etc/ceph/ceph.conf:z -v /home/cephadm/.ssh/id_rsa:/tmp/cephadm-ssh-key:z -v /home/cephadm/.ssh/id_rsa.pub:/tmp/cephadm-ssh-key.pub:z --entrypoint /usr/bin/ceph registry.suse.de/suse/containers/ses/7/containers/ses/7/ceph/ceph:15.2.0.108 cephadm set-priv-key -i /tmp/cephadm-ssh-key
DEBUG:cephadm:Releasing lock 140425224832336 on /run/cephadm/04e70252-0307-11eb-a869-5254000f2082.lock
DEBUG:cephadm:Lock 140425224832336 released on /run/cephadm/04e70252-0307-11eb-a869-5254000f2082.lock

**Comment by ricardoasmarques** [comment]
This failure happens because you are using `15.2.0.108` and `cephadm set-priv-key ` was only introduced on `v15.2.3-204-g0fcd99f277c`.

I'm closing this issue because ATM, `ceph-salt` requires the latest octopus release to be used.
