### ISSUE TITLE
Setting pillar_root to `/usr/share/ceph-salt/pillar` breaks ceph-salt

### ISSUE THREAD

**Issue by smithfarm** [ceph/ceph-salt#416]
/etc/salt/master has the following contents

```
    master: ++ cat /etc/salt/master
    master: user: salt
    master: syndic_user: salt
    master: log_level: info
    master: pillar_roots:
    master:   base:
    master:     - /usr/share/ceph-salt/pillar
```

ceph-salt is installed from RPM, version is:

```
master:~ # ceph-salt --version
ceph-salt 15.2.12+1601288307.gf6c5fd7
```

The directory exists and within it ceph-salt.sls:

```
master:~ # rpm -ql ceph-salt-formula | head
/usr/share/ceph-salt
/usr/share/ceph-salt/pillar
/usr/share/ceph-salt/pillar.conf.example
/usr/share/ceph-salt/pillar/ceph-salt.sls
/usr/share/ceph-salt/pillar/top.sls
```

The contents of `/usr/share/ceph-salt/pillar/ceph-salt.sls` are from ceph-salt.spec:

```
master:~ # cat /usr/share/ceph-salt/pillar/ceph-salt.sls
ceph-salt:

```

Invocation of `ceph-salt config` fails like this:

```
master:~ # ceph-salt config
Traceback (most recent call last):
  File "/usr/bin/ceph-salt", line 11, in <module>
    load_entry_point('ceph-salt==15.2.12+1601288307.gf6c5fd7', 'console_scripts', 'ceph-salt')()
  File "/usr/lib/python3.6/site-packages/ceph_salt/__init__.py", line 23, in ceph_salt_main
    cli(prog_name='ceph-salt')
  File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/ceph_salt/__init__.py", line 58, in config_shell
    if not run_config_shell():
  File "/usr/lib/python3.6/site-packages/ceph_salt/config_shell.py", line 1268, in run_config_shell
    generate_config_shell_tree(shell)
  File "/usr/lib/python3.6/site-packages/ceph_salt/config_shell.py", line 1189, in generate_config_shell_tree
    _generate_group_node(group_name, group_dict, root_node)
  File "/usr/lib/python3.6/site-packages/ceph_salt/config_shell.py", line 1183, in _generate_group_node
    _generate_option_node(option_name, option_dict, group_node)
  File "/usr/lib/python3.6/site-packages/ceph_salt/config_shell.py", line 1144, in _generate_option_node
    _generate_group_node(option_name, option_dict, parent)
  File "/usr/lib/python3.6/site-packages/ceph_salt/config_shell.py", line 1179, in _generate_group_node
    if handler and handler.default() is not None and handler.value()[0] is None:
  File "/usr/lib/python3.6/site-packages/ceph_salt/config_shell.py", line 276, in value
    val, _ = super().value()
  File "/usr/lib/python3.6/site-packages/ceph_salt/config_shell.py", line 71, in value
    return PillarManager.get(self.pillar_path), None
  File "/usr/lib/python3.6/site-packages/ceph_salt/salt_utils.py", line 285, in get
    res = cls._get_dict_value(cls.pillar_data, key)
  File "/usr/lib/python3.6/site-packages/ceph_salt/salt_utils.py", line 204, in _get_dict_value
    if path[0] in _dict:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by smithfarm** [comment]
Ah, invalid. The correct way to set it is:

```
pillar_roots:
  base:
    - /usr/share/ceph-salt
```
