### ISSUE TITLE
How to resolve ceph-salt status error?

### ISSUE THREAD

**Issue by 1397436824** [ceph/ceph-salt#481]
[root@master ~]# ceph-salt status
Failed to check if ceph orch is configured on minion 'master'

[root@master ~]# cat /etc/redhat-release 
CentOS Linux release 8.5.2111

[root@master ~]# uname -a
Linux master 4.18.0-348.el8.aarch64 #1 SMP Tue Oct 19 15:19:50 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

log:
2022-03-29 04:26:30,807 [DEBUG] [salt.client] jid 20220329082617273617 return from master
2022-03-29 04:26:30,808 [DEBUG] [salt.client] return event: {'master': {'ret': "'ceph_orch.configured' is not available.", 'out': 'nested', 'retcode': 1, 'jid': '20220329082617273617'}}
2022-03-29 04:26:30,910 [DEBUG] [salt.client] jid 20220329082617273617 found all minions {'master'}
2022-03-29 04:26:30,910 [DEBUG] [salt.transport.ipc] Closing IPCMessageSubscriber instance
2022-03-29 04:26:30,911 [ERROR] [ceph_salt] Failed to check if ceph orch is configured on minion 'master'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ceph_salt/__init__.py", line 23, in ceph_salt_main
    cli(prog_name='ceph-salt')
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/ceph_salt/__init__.py", line 71, in status
    if not run_status():
  File "/usr/local/lib/python3.6/site-packages/ceph_salt/config_shell.py", line 1284, in run_status
    host_ls = CephOrch.host_ls()
  File "/usr/local/lib/python3.6/site-packages/ceph_salt/salt_utils.py", line 373, in host_ls
    "on minion '{}'".format(minion))
ceph_salt.exceptions.CephSaltException: Failed to check if ceph orch is configured on minion 'master'

**Comment by 1397436824** [comment]
After executing the command "salt '*' saltutil.sync_all", it still exists
