### ISSUE TITLE
No bootstrap minion configured if there is no node has both MON and MGR

### ISSUE THREAD

**Issue by bk201** [ceph/ceph-salt#84]
In issue #42 a minion is tagged as bootstrapping role only when it has both MON and MGR roles, if this is a requirement, should we document it (maybe in sesdev or downstream doc) or add a check before deploying?

I tested sesdev with the following command:

```
sesdev create octopus --roles="[admin], [mon], [mgr], [storage]" dev
```

The deployment failed with:
```
    admin: ++ ceph-bootstrap config ls
    admin: o- / ......................................................................................................................... [...]
    admin:   o- Cluster ................................................................................................................. [...]
    admin:   | o- Minions ........................................................................................................ [Minions: 4]
    admin:   | | o- admin.dev.com .................................................................................................. [no roles]
    admin:   | | o- node1.dev.com ....................................................................................................... [mon]
    admin:   | | o- node2.dev.com ....................................................................................................... [mgr]
    admin:   | | o- node3.dev.com .................................................................................................. [no roles]
    admin:   | o- Roles ......................................................................... [Bootstrap minion: None, Minions w/ roles: 2]
    admin:   |   o- Mgr .......................................................................................................... [Minions: 1]
    admin:   |   | o- node2.dev.com .......................................................................................... [no other roles]
    admin:   |   o- Mon .......................................................................................................... [Minions: 1]
    admin:   |     o- node1.dev.com .......................................................................................... [no other roles]
    admin:   o- Containers .............................................................................................................. [...]
    admin:   | o- Images ................................................................................................................ [...]
    admin:   |   o- ceph ..................................................................... [docker.io/ceph/daemon-base:latest-master-devel]
    admin:   o- Deployment .............................................................................................................. [...]
    admin:   | o- Bootstrap ......................................................................................................... [enabled]
    admin:   | o- Dashboard ............................................................................................................. [...]
    admin:   | | o- password ............................................................................................................ [***]
    admin:   | | o- username .......................................................................................................... [admin]
    admin:   | o- Mgr ............................................................................................................... [enabled]
    admin:   | o- Mon ............................................................................................................... [enabled]
    admin:   | o- OSD ............................................................................................................... [enabled]
    admin:   o- SSH ............................................................................................................ [Key Pair set]
    admin:   | o- Private_Key ............................................................... [a4:b9:b1:3e:e7:a2:ba:fe:c6:d6:e5:82:e6:99:d3:24]
    admin:   | o- Public_Key ................................................................ [a4:b9:b1:3e:e7:a2:ba:fe:c6:d6:e5:82:e6:99:d3:24]
    admin:   o- Storage ................................................................................................................. [...]
    admin:   | o- Drive_Groups ............................................................................................................ [1]
    admin:   |   o- {"testing_dg_node3": {"host_pattern": "node3*", "data_devices": {"all": true}}} ..................................... [...]
    admin:   o- System_Update ........................................................................................................... [...]
    admin:   | o- Packages .......................................................................................................... [enabled]
    admin:   | o- Reboot ............................................................................................................ [enabled]
    admin:   o- Time_Server ......................................................................................................... [enabled]
    admin:     o- External_Servers ........................................................................................................ [1]
    admin:     | o- 0.pt.pool.ntp.org ................................................................................................... [...]
    admin:     o- Server_Hostname ............................................................................................. [admin.dev.com]
    admin: ++ zypper lr -upEP
    admin: #  | Alias               | Name                        | Enabled | GPG Check | Refresh | Priority | URI                                                                                              
    admin: ---+---------------------+-----------------------------+---------+-----------+---------+----------+--------------------------------------------------------------------------------------------------
    admin:  1 | octopus-repo1       | octopus-repo1               | Yes     | (r ) Yes  | No      |   98     | https://download.opensuse.org/repositories/filesystems:/ceph:/master:/upstream/openSUSE_Leap_15.2
    admin:  6 | repo-non-oss        | Non-OSS Repository          | Yes     | (r ) Yes  | No      |   99     | http://download.opensuse.org/distribution/leap/15.2/repo/non-oss/                                
    admin:  7 | repo-oss            | Main Repository             | Yes     | (r ) Yes  | No      |   99     | http://download.opensuse.org/distribution/leap/15.2/repo/oss/                                    
    admin: 10 | repo-update         | Main Update Repository      | Yes     | (r ) Yes  | No      |   99     | http://download.opensuse.org/update/leap/15.2/oss/                                               
    admin: 11 | repo-update-non-oss | Update Repository (Non-Oss) | Yes     | (r ) Yes  | No      |   99     | http://download.opensuse.org/update/leap/15.2/non-oss/                                           
    admin: ++ zypper info cephadm
    admin: ++ grep -E '(^Repo|^Version)'
    admin: Repository     : octopus-repo1                       
    admin: Version        : 15.1.0-lp152.833.1                  
    admin: ++ ceph-bootstrap --version
    admin: ceph-bootstrap 15.1.0+1581935293.g7a3134c
    admin: ++ stdbuf -o0 ceph-bootstrap -ldebug deploy --non-interactive
    admin: Checking if ceph-salt formula is available...
    admin: salt-master will be restarted to load ceph-salt formula
    admin: Could not find ceph-salt formula. Please check if ceph-salt-formula package is installed
Command '['vagrant', 'up']' failed: ret=1 stderr:
==> admin: An error occurred. The error will be shown after all tasks complete.
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

```

The error message doesn't make sense because the formula was installed correctly. After digging for a while, the minion log file provides some insight to the cause:

```
2020-02-19 08:41:27,500 [salt.minion      :1491][INFO    ][7109] User sudo_vagrant Executing command state.sls_exists with jid 20200219084127497627
2020-02-19 08:41:27,551 [salt.minion      :1618][INFO    ][11686] Starting a new job 20200219084127497627 with PID 11686
2020-02-19 08:41:27,701 [salt.state       :967 ][INFO    ][11686] Loading fresh modules for state activity
2020-02-19 08:41:27,764 [salt.utils.templates:180 ][ERROR   ][11686] Rendering exception occurred
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 394, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 13, in top-level template code
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'bootstrap_minion'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 169, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 404, in render_jinja_tmpl
    buf=tmplstr)
salt.exceptions.SaltRenderError: Jinja variable 'dict object' has no attribute 'bootstrap_minion'
2020-02-19 08:41:27,764 [salt.state       :3516][CRITICAL][11686] Rendering SLS 'base:ceph-salt' failed: Jinja variable 'dict object' has no attribute 'bootstrap_minion'
2020-02-19 08:41:27,764 [salt.minion      :1946][INFO    ][11686] Returning information for job: 20200219084127497627
```

**Comment by rimarques** [comment]
@bk201 thanks for reporting this issue. Implementing the missing validations is planned to be done on issue https://github.com/SUSE/ceph-bootstrap/issues/7

The idea is to have a “ceph-bootstrap status” command that checks if the current config is valid. The same validations that are implemented I the “status” command should then be executed before the deployment.

**Comment by ricardoasmarques** [comment]
@bk201 thanks for reporting this issue. Implementing the missing validations is planned to be done on issue https://github.com/SUSE/ceph-bootstrap/issues/7

The idea is to have a “ceph-bootstrap status” command that checks if the current config is valid. The same validations that are implemented I the “status” command should then be executed before the deployment.

**Comment by bk201** [comment]
Thanks! Didn't notice it's mentioned in #7. Close this.
