### ISSUE TITLE
click: `de_DE.UTF-8`

### ISSUE THREAD

**Issue by sebastian-philipp** [ceph/ceph-salt#86]
```
scalability-master:~ # ceph-bootstrap deploy
Traceback (most recent call last):
  File "/usr/bin/ceph-bootstrap", line 11, in <module>
    load_entry_point('ceph-bootstrap==15.1.0+1581935293.g7a3134c', 'console_scripts', 'ceph-bootstrap')()
  File "/usr/lib/python3.6/site-packages/ceph_bootstrap/__init__.py", line 55, in ceph_bootstrap_main
    cli(prog_name='ceph-bootstrap')
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 676, in main
    _verify_python3_env()
  File "/usr/lib/python3.6/site-packages/click/_unicodefun.py", line 118, in _verify_python3_env
    'for mitigation steps.' + extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.  Consult http://click.pocoo.org/python3/for mitigation steps.

This system supports the C.UTF-8 locale which is recommended.
You might be able to resolve your issue by exporting the
following environment variables:

    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8

Click discovered that you exported a UTF-8 locale
but the locale system could not pick up from it because
it does not exist.  The exported locale is "de_DE.UTF-8" but it
is not supported
```

**Comment by sebastian-philipp** [comment]
please reopen, if this is still reproducible
