### ISSUE TITLE
OSD deployment fails due to invalid drive groups syntax

### ISSUE THREAD

**Issue by smithfarm** [ceph/ceph-salt#96]
<h2>Problem</h2>

Due to a recently introduced regression, ceph-salt stopped deploying OSDs.

<h2>Symptom</h2>

The "Deploying OSD groups 1/1" step finishes immediately, and then `sesdev create octopus ... --qa-test ...` fails because the cluster has zero OSDs.

<h2>Analysis</h2>

ceph-salt uses a command like the following to deploy OSDs:

```
echo '{\"testing_dg_admin\": {\"host_pattern\": \"admin*\", \"data_devices\": {\"all\": true}}}' | ceph orch osd create -i -
```

When I try this command manually, it fails:

```
admin:~ # echo '{\"testing_dg_admin\": {\"host_pattern\": \"admin*\", \"data_devices\": {\"all\": true}}}' | ceph orch osd create -i -
Error EINVAL: Traceback (most recent call last):
  File "/usr/share/ceph/mgr/mgr_module.py", line 1070, in _handle_command
    return self.handle_command(inbuf, cmd)
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 191, in handle_command
    return dispatch[cmd['prefix']].call(self, cmd, inbuf)
  File "/usr/share/ceph/mgr/mgr_module.py", line 309, in call
    return self.func(mgr, **kwargs)
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 153, in <lambda>
    wrapper_copy = lambda *l_args, **l_kwargs: wrapper(*l_args, **l_kwargs)
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 144, in wrapper
    return func(*args, **kwargs)
  File "/usr/share/ceph/mgr/orchestrator/module.py", line 437, in _create_osd
    dgs = DriveGroupSpecs(yaml.load(inbuf))
  File "/usr/lib/python3.6/site-packages/ceph/deployment/drive_group.py", line 117, in __init__
    self.build_drive_groups()
  File "/usr/lib/python3.6/site-packages/ceph/deployment/drive_group.py", line 122, in build_drive_groups
    (drive_group_spec, name=drive_group_name))
  File "/usr/lib/python3.6/site-packages/ceph/deployment/drive_group.py", line 228, in from_json
    "Feature <{}> is not supported".format(applied_filter))
ceph.deployment.drive_group.DriveGroupValidationError: Failed to validate Drive Group: Feature <\"host_pattern\"> is not supported

admin:~ # echo $?
22
```

When I change the single quotes that are around the JSON in the `echo` statement to double quotes, it succeeds. It also succeeds with the single-quotes, provided I remove the backslashes from the JSON.

**Comment by smithfarm** [comment]
This is wrong. Here is the real issue: https://tracker.ceph.com/issues/44270
